<?php

namespace Database\Seeders;

use App\Models\Permohonan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PermohonanSeeder extends Seeder
{
    public function run(): void
    {
        // Bersihkan data permohonan lama agar tidak duplikat
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('permohonans')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $permohonans = [
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0001',
                'nama_usaha' => 'Kedai Kopi Janji Kita',
                'nama_perusahaan' => 'CV Kopi Nusantara',
                'pemilik' => 'Ahmad Sodikin',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'CV',
                'nik' => '3578012345670001',
                'tanggal_permohonan' => Carbon::now()->subDays(5)->toDateString(),
                'nib' => '9120001234567',
                'alamat_perusahaan' => 'Jl. Dharmahusada No. 12, Surabaya',
                'sektor' => 'Dinkopdag',
                'kbli' => '56101', // Restoran
                'modal_usaha' => 75000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0001',
                'nama_perizinan' => 'Sertifikat Standar Usaha Jasa Makanan dan Minuman',
                'skala_usaha' => 'Kecil',
                'risiko' => 'Menengah Rendah',
                'jangka_waktu' => 3,
                'no_telephone' => '081234567890',
                'deadline' => Carbon::now()->addDays(5)->toDateString(),
                'verifikator' => 'Rina Amalia',
                'status' => 'Menunggu',
                'verifikasi_dpmptsp' => 'Berkas Sesuai',
                'verifikasi_pd_teknis' => 'Menunggu Verifikasi',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0002',
                'nama_usaha' => 'Klinik Sehat Sejahtera',
                'nama_perusahaan' => 'PT Medika Utama',
                'pemilik' => 'dr. Budi Santoso',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'PT',
                'nik' => '3578012345670002',
                'tanggal_permohonan' => Carbon::now()->subDays(10)->toDateString(),
                'nib' => '9120001234568',
                'alamat_perusahaan' => 'Jl. Kertajaya Indah No. 45, Surabaya',
                'sektor' => 'Dinkes',
                'kbli' => '86104', // Aktivitas Klinik Swasta
                'modal_usaha' => 500000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0002',
                'nama_perizinan' => 'Izin Operasional Klinik Pratama',
                'skala_usaha' => 'Menengah',
                'risiko' => 'Menengah Tinggi',
                'jangka_waktu' => 5,
                'no_telephone' => '082345678901',
                'deadline' => Carbon::now()->addDays(2)->toDateString(),
                'verifikator' => 'Hendra Wijaya',
                'status' => 'Menunggu',
                'verifikasi_dpmptsp' => 'Berkas Sesuai',
                'verifikasi_pd_teknis' => 'Menunggu Verifikasi',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0003',
                'nama_usaha' => 'Toko Kelontong Berkah',
                'nama_perusahaan' => null,
                'pemilik' => 'Siti Aminah',
                'jenis_pelaku_usaha' => 'Orang Perseorangan',
                'jenis_badan_usaha' => null,
                'nik' => '3578012345670003',
                'tanggal_permohonan' => Carbon::now()->subDays(12)->toDateString(),
                'nib' => '9120001234569',
                'alamat_perusahaan' => 'Jl. Gubeng Masjid No. 5, Surabaya',
                'sektor' => 'Dinkopdag',
                'kbli' => '47111', // Perdagangan Eceran Berbagai Macam Barang
                'modal_usaha' => 15000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0003',
                'nama_perizinan' => 'Nomor Induk Berusaha (NIB)',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 1,
                'no_telephone' => '083456789012',
                'deadline' => Carbon::now()->subDays(2)->toDateString(), // OVERDUE
                'verifikator' => 'Rina Amalia',
                'status' => 'Terlambat',
                'verifikasi_dpmptsp' => 'Berkas Belum Sesuai',
                'verifikasi_pd_teknis' => 'Menunggu Perbaikan',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0004',
                'nama_usaha' => 'Jasa Angkutan Barang Logistik',
                'nama_perusahaan' => 'PT Surabaya Trans Logistik',
                'pemilik' => 'Joko Susilo',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'PT',
                'nik' => '3578012345670004',
                'tanggal_permohonan' => Carbon::now()->subDays(4)->toDateString(),
                'nib' => '9120001234570',
                'alamat_perusahaan' => 'Jl. Perak Barat No. 100, Surabaya',
                'sektor' => 'Dishub',
                'kbli' => '49221', // Angkutan Jalan Untuk Barang
                'modal_usaha' => 1200000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0004',
                'nama_perizinan' => 'Izin Penyelenggaraan Angkutan Barang',
                'skala_usaha' => 'Besar',
                'risiko' => 'Tinggi',
                'jangka_waktu' => 5,
                'no_telephone' => '084567890123',
                'deadline' => Carbon::now()->addDays(10)->toDateString(),
                'verifikator' => 'Adi Nugroho',
                'status' => 'Diterima',
                'verifikasi_dpmptsp' => 'Berkas Sesuai',
                'verifikasi_pd_teknis' => 'Berkas Disetujui',
                'terbit' => Carbon::now()->toDateString(),
                'pemroses_dan_tgl_surat' => 'Penerbitan Berkas / ' . Carbon::now()->locale('id')->translatedFormat('d F Y'),
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0005',
                'nama_usaha' => 'Rumah Makan Padang Minang Raso',
                'nama_perusahaan' => 'CV Minang Raso',
                'pemilik' => 'Edi Chaniago',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'CV',
                'nik' => '3578012345670005',
                'tanggal_permohonan' => Carbon::now()->subDays(6)->toDateString(),
                'nib' => '9120001234571',
                'alamat_perusahaan' => 'Jl. Manyar Kertoarjo No. 89, Surabaya',
                'sektor' => 'Disbudpar',
                'kbli' => '56102', // Rumah Minum/Kafe
                'modal_usaha' => 90000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0005',
                'nama_perizinan' => 'TDUP (Tanda Daftar Usaha Pariwisata) - Penyediaan Makanan',
                'skala_usaha' => 'Kecil',
                'risiko' => 'Menengah Rendah',
                'jangka_waktu' => 3,
                'no_telephone' => '085678901234',
                'deadline' => Carbon::now()->addDays(4)->toDateString(),
                'verifikator' => 'Rina Amalia',
                'status' => 'Dikembalikan',
                'verifikasi_dpmptsp' => 'Berkas Dikembalikan',
                'verifikasi_pd_teknis' => 'Berkas Kurang Dokumen',
                'pengembalian' => Carbon::now()->subDays(1)->toDateString(),
                'keterangan_pengembalian' => 'Dokumen AMDAL/UKL-UPL belum diunggah secara lengkap.',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0006',
                'nama_usaha' => 'Industri Pengolahan Kayu Lestari',
                'nama_perusahaan' => 'PT Lestari Kayu Abadi',
                'pemilik' => 'Hendry Setiawan',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'PT',
                'nik' => '3578012345670006',
                'tanggal_permohonan' => Carbon::now()->subDays(8)->toDateString(),
                'nib' => '9120001234572',
                'alamat_perusahaan' => 'Kawasan Industri Rungkut (SIER) Blok G-12, Surabaya',
                'sektor' => 'Disperinaker',
                'kbli' => '16101', // Industri Penggergajian Kayu
                'modal_usaha' => 3000000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0006',
                'nama_perizinan' => 'Izin Usaha Industri (IUI) Pengolahan Kayu',
                'skala_usaha' => 'Besar',
                'risiko' => 'Menengah Tinggi',
                'jangka_waktu' => 5,
                'no_telephone' => '086789012345',
                'deadline' => Carbon::now()->addDays(7)->toDateString(),
                'verifikator' => 'Gunawan Wibisono',
                'status' => 'Ditolak',
                'verifikasi_dpmptsp' => 'Berkas Ditolak',
                'verifikasi_pd_teknis' => 'Berkas Tidak Sesuai Syarat',
                'keterangan' => 'Lokasi usaha berada di zona hijau yang dilarang untuk industri berat berdasarkan RT/RW Kota.',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0007',
                'nama_usaha' => 'Peternakan Ayam Telur Emas',
                'nama_perusahaan' => null,
                'pemilik' => 'Suparman',
                'jenis_pelaku_usaha' => 'Orang Perseorangan',
                'jenis_badan_usaha' => null,
                'nik' => '3578012345670007',
                'tanggal_permohonan' => Carbon::now()->subDays(3)->toDateString(),
                'nib' => '9120001234573',
                'alamat_perusahaan' => 'Kel. Pakal RT 03/RW 04, Pakal, Surabaya',
                'sektor' => 'Dkpp',
                'kbli' => '01461', // Budidaya Ayam Ras Petelur
                'modal_usaha' => 45000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0007',
                'nama_perizinan' => 'Persetujuan Pemenuhan Standar Peternakan Rakyat',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Menengah Rendah',
                'jangka_waktu' => 2,
                'no_telephone' => '087890123456',
                'deadline' => Carbon::now()->addDays(8)->toDateString(),
                'verifikator' => 'Rina Amalia',
                'status' => 'Menunggu',
                'verifikasi_dpmptsp' => 'Berkas Sesuai',
                'verifikasi_pd_teknis' => 'Menunggu Verifikasi',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0008',
                'nama_usaha' => 'Depo Pengelolaan Limbah Hijau',
                'nama_perusahaan' => 'CV Hijau Lestari Indonesia',
                'pemilik' => 'Ferry Hermawan',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'CV',
                'nik' => '3578012345670008',
                'tanggal_permohonan' => Carbon::now()->subDays(9)->toDateString(),
                'nib' => '9120001234574',
                'alamat_perusahaan' => 'Margomulyo Indah Blok F-8, Surabaya',
                'sektor' => 'Dlh',
                'kbli' => '38210', // Pengolahan Limbah Non-B3
                'modal_usaha' => 350000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0008',
                'nama_perizinan' => 'Persetujuan Teknis Lingkungan (SPPL/UKL-UPL)',
                'skala_usaha' => 'Menengah',
                'risiko' => 'Menengah Tinggi',
                'jangka_waktu' => 3,
                'no_telephone' => '088901234567',
                'deadline' => Carbon::now()->addDays(1)->toDateString(),
                'verifikator' => 'Indah Permata',
                'status' => 'Menunggu',
                'verifikasi_dpmptsp' => 'Berkas Sesuai',
                'verifikasi_pd_teknis' => 'Menunggu Verifikasi',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0009',
                'nama_usaha' => 'Apotek Prima Medika',
                'nama_perusahaan' => null,
                'pemilik' => 'Apoteker Laila Sari',
                'jenis_pelaku_usaha' => 'Orang Perseorangan',
                'jenis_badan_usaha' => null,
                'nik' => '3578012345670009',
                'tanggal_permohonan' => Carbon::now()->subDays(7)->toDateString(),
                'nib' => '9120001234575',
                'alamat_perusahaan' => 'Jl. Raya Darmo No. 120, Surabaya',
                'sektor' => 'Dinkes',
                'kbli' => '47721', // Perdagangan Eceran Barang Farmasi di Apotek
                'modal_usaha' => 150000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0009',
                'nama_perizinan' => 'Surat Izin Apotek (SIA)',
                'skala_usaha' => 'Kecil',
                'risiko' => 'Menengah Tinggi',
                'jangka_waktu' => 3,
                'no_telephone' => '089012345678',
                'deadline' => Carbon::now()->addDays(3)->toDateString(),
                'verifikator' => 'Hendra Wijaya',
                'status' => 'Dikembalikan',
                'verifikasi_dpmptsp' => 'Berkas Dikembalikan',
                'verifikasi_pd_teknis' => 'Berkas Perlu Revisi Tata Ruang',
                'pengembalian' => Carbon::now()->subDays(2)->toDateString(),
                'keterangan_pengembalian' => 'Sertifikat STRA Apoteker Penanggung Jawab sudah kedaluwarsa.',
                'menghubungi' => Carbon::now()->subDays(1)->toDateString(),
                'keterangan_menghubungi' => 'Telah dihubungi via WA untuk segera mengunggah perpanjangan STRA.',
                'status_menghubungi' => 'Selesai dihubungi',
            ],
            [
                'user_id' => 2, // dpmptsp
                'no_permohonan' => 'PMH-20260827-0010',
                'nama_usaha' => 'Pembangunan Apartemen Skyview',
                'nama_perusahaan' => 'PT Skyview Properti Indonesia',
                'pemilik' => 'Ir. Hartono',
                'jenis_pelaku_usaha' => 'Badan Usaha',
                'jenis_badan_usaha' => 'PT',
                'nik' => '3578012345670010',
                'tanggal_permohonan' => Carbon::now()->subDays(15)->toDateString(),
                'nib' => '9120001234576',
                'alamat_perusahaan' => 'Jl. HR Muhammad No. 50, Surabaya',
                'sektor' => 'Dprkpp',
                'kbli' => '41011', // Konstruksi Gedung Hunian
                'modal_usaha' => 25000000000.00,
                'jenis_proyek' => 'Utama',
                'no_proyek' => 'PRJ-2026-0010',
                'nama_perizinan' => 'Persetujuan Bangunan Gedung (PBG)',
                'skala_usaha' => 'Besar',
                'risiko' => 'Tinggi',
                'jangka_waktu' => 12,
                'no_telephone' => '081122334455',
                'deadline' => Carbon::now()->addDays(15)->toDateString(),
                'verifikator' => 'Dewi Lestari',
                'status' => 'Menunggu',
                'verifikasi_dpmptsp' => 'Berkas Sesuai',
                'verifikasi_pd_teknis' => 'Menunggu Verifikasi',
            ],
        ];

        foreach ($permohonans as $permohonan) {
            $createdPermohonan = Permohonan::create($permohonan);

            // Tambah log awal untuk audit trail
            $createdPermohonan->logs()->create([
                'user_id' => $permohonan['user_id'],
                'status_sebelum' => 'Menunggu',
                'status_sesudah' => $permohonan['status'],
                'keterangan' => 'Permohonan berhasil didaftarkan di sistem.',
                'action' => 'create',
                'old_data' => null,
                'new_data' => json_encode($permohonan)
            ]);
        }
    }
}
