<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Permohonan;
use App\Models\User;
use Carbon\Carbon;

class PermohonanUlangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil user untuk testing
        $users = User::all();
        if ($users->isEmpty()) {
            $this->command->error('No users found. Please run UserSeeder first.');
            return;
        }

        $this->command->info('Creating permohonan ulang data based on provided table...');

        // Data permohonan ulang berdasarkan tabel yang diberikan
        $data = [
            [
                'no_permohonan' => 'UL-202504291626428624593',
                'no_proyek' => '202504-2908-5233-9874-388',
                'tanggal_permohonan' => '2025-05-03',
                'nib' => '8120210000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'PT',
                'nama_perusahaan' => 'SAPTASUMBER LANCAR',
                'nama_usaha' => 'PT. SAPTASUMBER LANCAR',
                'alamat_perusahaan' => 'Jl. Tambak Langon Indah 1/27 Surabaya (Lama: Jl. Tambak Langon Indah)',
                'modal_usaha' => 20600000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Ahmad Wijaya, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => 'UL-202209191652027222398',
                'no_proyek' => '202209-0914-1531-4755-545',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '0809220113861',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'SAMSUDIN, SAMSUL',
                'nama_usaha' => 'Persewaan Gudang',
                'alamat_perusahaan' => 'Jl. Margomulyo Indah Blok E Kav. 4 Surabaya, (lama Blok A Kav.38), Kel. Buntaran, Kec. Tandes, Kota Surabaya, Jawa Timur, 60184',
                'modal_usaha' => 20000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Budi Santoso, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021110164014101',
                'no_proyek' => '202505-0210-1553-7743-322',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '9120010000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'UD. KING KOK',
                'nama_usaha' => '83',
                'alamat_perusahaan' => 'JL KEDINDING TENGAH JAYA II NO. 83 (LAMA: JL. KEDINDING TENGAH JAYA II)',
                'modal_usaha' => 200000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Citra Dewi, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021101076034928',
                'no_proyek' => '202505-0210-1104-1502-150',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '9120010000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'UD. KING KOK',
                'nama_usaha' => '81',
                'alamat_perusahaan' => 'JL KEDINDING TENGAH JAYA II NO. 81 (LAMA: JL KEDINDING TENGAH JAYA II)',
                'modal_usaha' => 200000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Dedi Kurniawan, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021048436073172',
                'no_proyek' => '202505-0210-0340-9121-746',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '9120010000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'UD. KING KOK',
                'nama_usaha' => 'GUDANG',
                'alamat_perusahaan' => 'JL KEDINDING TENGAH JAYA II NO. 81 (LAMA: JL KEDINDING TENGAH JAYA II)',
                'modal_usaha' => 200000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Eka Putri, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021616241896624',
                'no_proyek' => '202505-0215-2855-7978-250',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '9120320000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'UD. BINTANG MULIA',
                'nama_usaha' => 'UD. BINTANG MULIA',
                'alamat_perusahaan' => 'Jalan Kenjeran 516 Kav 27-29',
                'modal_usaha' => 50000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Fajar Nugroho, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021640141739840',
                'no_proyek' => '202505-0215-3632-2579-012',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '2301250000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'HERMANTO',
                'nama_usaha' => 'GUDANG',
                'alamat_perusahaan' => 'Komp. Pergudangan Mutiara Margomulyo Indah No. 14 (Lama: Jl. Margomulyo Indah Blok E Kav. 3)',
                'modal_usaha' => 27000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Gita Sari, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021635528588644',
                'no_proyek' => '202505-0214-1459-8387-032',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '2301250000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'HERMANTO',
                'nama_usaha' => 'GUDANG',
                'alamat_perusahaan' => 'Jl. Margomulyo Indah E Kav. 28 (Lama: Jl. Mutiara Margomulyo Indah Blok A No. 15) Surabaya',
                'modal_usaha' => 27000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Hendra Pratama, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021644194512130',
                'no_proyek' => '202505-0216-1705-2161-083',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '2301250000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'HERMANTO',
                'nama_usaha' => 'GUDANG',
                'alamat_perusahaan' => 'Komp. Pergudangan Mutiara Margomulyo Indah No. 6 (Lama: Jl Margomulyo Indah Blok E Kav. 10) Surabaya',
                'modal_usaha' => 27000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Indah Lestari, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021330209982564',
                'no_proyek' => '202504-2911-4201-7854-786',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '1404230000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'DJONI RUDY',
                'nama_usaha' => 'pergudangan',
                'alamat_perusahaan' => 'JL. ROMOKALISARI INDUSTRI SENTOSA 1/33 (LAMA JL. ROMOKALISARI INDAH SANTOSO I KAV. D-8)',
                'modal_usaha' => 50000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Joko Susilo, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505020909383119036',
                'no_proyek' => '202505-0208-5134-9736-600',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '2910220000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'LIM HENDRA',
                'nama_usaha' => 'C-15',
                'alamat_perusahaan' => 'KOMP. PERGUDANGAN MARGOMULYO JAYA BLOK C-15',
                'modal_usaha' => 50000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Kecil',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Ahmad Wijaya, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505020916238892023',
                'no_proyek' => '202505-0208-5638-1809-877',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '2910220000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'LIM HENDRA',
                'nama_usaha' => 'C-16',
                'alamat_perusahaan' => 'KOMP. PERGUDANGAN MARGOMULYO JAYA BLOK C-16',
                'modal_usaha' => 50000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Budi Santoso, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505020955067889569',
                'no_proyek' => '202505-0209-2309-2543-200',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '9120210000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'UD. ANUGERAH GRAHA SUKSES',
                'nama_usaha' => 'Gudang penyimpanan',
                'alamat_perusahaan' => 'KOMP PERGUDANGAN MUTIARA TAMBAK LANGON INDAH BLOK D KAV 14 (LAMA: JL. MUTIARA TAMBAK LANGON/TAMBAK LANGON INDAH BLOK D KAV 14)',
                'modal_usaha' => 100000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Citra Dewi, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021315545945118',
                'no_proyek' => '202505-0209-5236-1082-192',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '1404230000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'DIONI RUDY',
                'nama_usaha' => 'PERGUDANGAN SENTOSA',
                'alamat_perusahaan' => 'JL. ROMOKALISARI INDUSTRI SENTOSA 1/21 (LAMA JL. ROMOKALISARI INDAH SANTOSA I KAV D-1) SURABAYA',
                'modal_usaha' => 25000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Dedi Kurniawan, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021332166336829',
                'no_proyek' => '202210-2607-4722-8958-328',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '2610220000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'LENBACH SASTRA',
                'nama_usaha' => 'Gudang dan Penyimpanan',
                'alamat_perusahaan' => 'Jl. Kyai Tambak Deres No. 3-5',
                'modal_usaha' => 200000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Eka Putri, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021401415267866',
                'no_proyek' => '202505-0210-5938-0409-228',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '1404230000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'DJONI RUDY',
                'nama_usaha' => 'PERGUDANGAN SENTOSA',
                'alamat_perusahaan' => 'JL. ROMOKALISARI INDUSTRI SENTOSA 1/31 (LAMA JL. ROMOKALISARI INDAH SANTOSA I KAV D-7) SURABAYA',
                'modal_usaha' => 25000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Fajar Nugroho, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021423564007023',
                'no_proyek' => '202505-0214-0340-1813-018',
                'tanggal_permohonan' => '2025-05-02',
                'nib' => '410220000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'ZULCHA MINTACHUS SANIA',
                'nama_usaha' => 'pergudangan',
                'alamat_perusahaan' => 'Jalan Gunung Anyar Tambak III No. 41 (Lama: Jl. gunung Anyar Tambak No. 41)',
                'modal_usaha' => 10000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Gita Sari, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505032210453098723',
                'no_proyek' => '202505-0321-2702-6859-362',
                'tanggal_permohonan' => '2025-05-03',
                'nib' => '2402220000000',
                'kbli' => '46631',
                'inputan_teks' => 'Perdagangan Besar Barang Logam Untuk Bahan Konstruksi',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'WINARTO KUNCORO',
                'nama_usaha' => 'Perdagangan',
                'alamat_perusahaan' => 'Jl. Romokalisari No. 17 Surabaya (Jl. Tambak Osowilangun)',
                'modal_usaha' => 200000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Hendra Pratama, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505051415059867556',
                'no_proyek' => '202505-0513-3546-0637-737',
                'tanggal_permohonan' => '2025-05-05',
                'nib' => '505250000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'LIEM BIEK LANYULANDA C',
                'nama_usaha' => 'Gudang penyimpanan',
                'alamat_perusahaan' => 'JL. MARGOMULYO PERMAI I BLOK AD KAV 9B',
                'modal_usaha' => 100000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Indah Lestari, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505051156049796194',
                'no_proyek' => '202504-3011-0038-8371-757',
                'tanggal_permohonan' => '2025-05-05',
                'nib' => '3004250000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'YENNY',
                'nama_usaha' => 'Yenny Jaya',
                'alamat_perusahaan' => 'Komp. Pergudangan Margomulyo Jaya Blok B-19 Surabaya.',
                'modal_usaha' => 300000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Joko Susilo, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505051613106809540',
                'no_proyek' => '202504-2911-0621-9693-141',
                'tanggal_permohonan' => '2025-05-05',
                'nib' => '2904250000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'DANNY GOENTORO',
                'nama_usaha' => 'GUDANG',
                'alamat_perusahaan' => 'Jl. Margomulyo Permai VIII/Blok R.4-R.4A',
                'modal_usaha' => 100000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Ahmad Wijaya, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505050932366223965',
                'no_proyek' => '202504-2911-0621-9693-141',
                'tanggal_permohonan' => '2025-05-05',
                'nib' => '1905220000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'AKWAN',
                'nama_usaha' => 'Gudang Penyimpanan',
                'alamat_perusahaan' => 'JL. MARGOMULYO PERMAI NO 46 H16',
                'modal_usaha' => 100000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Budi Santoso, S.E.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021528433293086',
                'no_proyek' => '202505-0210-2145-0451-923',
                'tanggal_permohonan' => '2025-05-05',
                'nib' => '1404230000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'DJONI RUDY',
                'nama_usaha' => 'PERGUDANGAN SENTOSA',
                'alamat_perusahaan' => 'JL. ROMOKALISARI INDUSTRI SENTOSA III/10 (LAMA JL. ROMOKALISARI INDAH SANTOSA III KAV D-22)',
                'modal_usaha' => 20000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Citra Dewi, S.H.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
            [
                'no_permohonan' => '1-202505021616241896624',
                'no_proyek' => '202505-0215-2855-7978-250',
                'tanggal_permohonan' => '2025-05-06',
                'nib' => '9120320000000',
                'kbli' => '52101',
                'inputan_teks' => 'Pergudangan dan Penyimpanan',
                'jenis_pelaku_usaha' => 'Perseorangan',
                'nama_perusahaan' => 'UD. BINTANG MULIA',
                'nama_usaha' => 'UD. BINTANG MULIA',
                'alamat_perusahaan' => 'Jl.Kalijudan Timur No.31 (Lama: Jl.Kenjeran 516 Kav.27-29).',
                'modal_usaha' => 50000000,
                'jenis_proyek' => 'Utama',
                'nama_perizinan' => 'Tanda Daftar Gudang',
                'skala_usaha' => 'Mikro',
                'risiko' => 'Rendah',
                'jangka_waktu' => 2,
                'sektor' => 'PERDAGANGAN',
                'status' => 'Dikembalikan',
                'verifikator' => 'Dedi Kurniawan, S.T.',
                'verifikasi_pd_teknis' => 'Berkas Diperbaiki',
                'verifikasi_dpmptsp' => 'Perlu Perbaikan',
            ],
        ];

        // Buat data permohonan ulang
        foreach ($data as $index => $item) {
            $user = $users->random();
            
            // Pastikan nomor permohonan unik dengan prefix UL-
            $noPermohonan = 'UL-' . ($index + 1) . '-' . substr($item['no_permohonan'], 2);
            
            Permohonan::create([
                'no_permohonan' => $noPermohonan,
                'no_proyek' => $item['no_proyek'],
                'tanggal_permohonan' => $item['tanggal_permohonan'],
                'nib' => $item['nib'],
                'alamat_perusahaan' => $item['alamat_perusahaan'],
                'sektor' => $item['sektor'],
                'nama_usaha' => $item['nama_usaha'],
                'jenis_pelaku_usaha' => $item['jenis_pelaku_usaha'],
                'nama_perusahaan' => $item['nama_perusahaan'],
                'kbli' => $item['kbli'],
                'inputan_teks' => $item['inputan_teks'],
                'modal_usaha' => $item['modal_usaha'],
                'jenis_proyek' => $item['jenis_proyek'],
                'nama_perizinan' => $item['nama_perizinan'],
                'skala_usaha' => $item['skala_usaha'],
                'risiko' => $item['risiko'],
                'jangka_waktu' => $item['jangka_waktu'],
                'no_telephone' => '0812345678' . str_pad($index + 1, 2, '0', STR_PAD_LEFT),
                'deadline' => Carbon::parse($item['tanggal_permohonan'])->addDays(30),
                'verifikator' => $item['verifikator'],
                'verifikasi_dpmptsp' => $item['verifikasi_dpmptsp'],
                'verifikasi_pd_teknis' => $item['verifikasi_pd_teknis'],
                'status' => $item['status'],
                'user_id' => $user->id,
                'created_at' => Carbon::parse($item['tanggal_permohonan']),
                'updated_at' => Carbon::parse($item['tanggal_permohonan']),
            ]);
        }

        $this->command->info('Created 24 permohonan ulang records based on provided table:');
        $this->command->info('- All status: Dikembalikan (permohonan ulang)');
        $this->command->info('- Sektor: PERDAGANGAN');
        $this->command->info('- KBLI: 52101 (Pergudangan dan Penyimpanan)');
        $this->command->info('- Nama Perizinan: Tanda Daftar Gudang');
        $this->command->info('- Jangka Waktu: 2 Hari');
        $this->command->info('- Format: Based on real data from provided table');
    }
}
